spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

logging.level.org.bamboomy.c44=DEBUG

server.port=7778

server.url=http://localhost:8080

identifierHash=b2e732c3bf017fd522daa46d754de02c
